const shoppingListData = [
    { id: 1, category: "Produce (Vihannesosasto)", name: "Pre-packaged Salad Greens", quantity: "4 bags", checked: false },
    { id: 2, category: "Produce (Vihannesosasto)", name: "Baby Spinach", quantity: "1 bag", checked: false },
    { id: 3, category: "Produce (Vihannesosasto)", name: "Avocados", quantity: "2", checked: false },
    { id: 4, category: "Produce (Vihannesosasto)", name: "Bananas", quantity: "2-3", checked: false },
    { id: 5, category: "Produce (Vihannesosasto)", name: "Oranges or Clementines", quantity: "2-3", checked: false },
    { id: 6, category: "Produce (Vihannesosasto)", name: "Fresh Berries", quantity: "1 punnet", checked: false },
    { id: 7, category: "Produce (Vihannesosasto)", name: "Lemon Juice (Bottle)", quantity: "1", checked: false },
    { id: 8, category: "Produce (Vihannesosasto)", name: "Carrot Sticks", quantity: "optional", checked: false },
    { id: 9, category: "Breads & Bakery (Leipäosasto)", name: "100% Rye Bread / Ruisleipä", quantity: "1 loaf", checked: false },
    { id: 10, category: "Chilled & Dairy", name: "Maitorahka or Raejuusto", quantity: "2 large tubs", checked: false },
    { id: 11, category: "Chilled & Dairy", name: "Skimmed Milk / Rasvaton Maito", quantity: "1 carton", checked: false },
    { id: 12, category: "Chilled & Dairy", name: "Pre-cooked Chicken Slices", quantity: "4 packs", checked: false },
    { id: 13, category: "Chilled & Dairy", name: "Smoked Salmon", quantity: "2 packs", checked: false },
    { id: 14, category: "Chilled & Dairy", name: "Low-fat Cream Cheese", quantity: "1 tub", checked: false },
    { id: 15, category: "Chilled & Dairy", name: "Pre-cooked Hard-Boiled Eggs", quantity: "optional", checked: false },
    { id: 16, category: "Pantry & Canned Goods", name: "Protein Powder", quantity: "1 tub", checked: false },
    { id: 17, category: "Pantry & Canned Goods", name: "Oat Flakes / Kaurahiutaleet", quantity: "1 bag", checked: false },
    { id: 18, category: "Pantry & Canned Goods", name: "Unsalted Nuts (Walnuts, Almonds)", quantity: "2 bags", checked: false },
    { id: 19, category: "Pantry & Canned Goods", name: "Seeds (Flax, Chia, etc.)", quantity: "1 bag", checked: false },
    { id: 20, category: "Pantry & Canned Goods", name: "Canned Tuna in Water", quantity: "3 cans", checked: false },
    { id: 21, category: "Pantry & Canned Goods", name: "Chickpeas / Kikherneet", quantity: "3 cartons", checked: false },
    { id: 22, category: "Pantry & Canned Goods", name: "Large White Beans", quantity: "1 carton", checked: false },
    { id: 23, category: "Pantry & Canned Goods", name: "Jarred Roasted Bell Peppers", quantity: "1 jar", checked: false },
    { id: 24, category: "Pantry & Canned Goods", name: "Canned Sweet Corn", quantity: "1-2 cans", checked: false },
    { id: 25, category: "Pantry & Canned Goods", name: "Pitted Olives", quantity: "1 jar", checked: false },
    { id: 26, category: "Frozen Foods (Pakasteet)", name: "Frozen Berries", quantity: "1 large bag", checked: false },
    { id: 27, category: "Frozen Foods (Pakasteet)", name: "Frozen Vegetable Mix", quantity: "1-2 bags", checked: false }
];